// strings.js — every player-visible string. Swap this file to localize.
export const STR = {
  title: 'BLUEBIRD PARK',
  subtitle: 'Big mountain run — glades · crystal cave · cliff cannon · life-size jump line · lodge roof gap',
  pressStart: 'Click or press SPACE to drop in',
  controls: [
    ['A / D or ← →', 'carve · spin (in air AND on rails)'],
    ['W / S', 'tuck / brake · front / backflip (air)'],
    ['W+A/D · S+A/D', 'misty · cork (in air)'],
    ['SPACE (hold)', 'load legs, release to pop · pop off rails'],
    ['J / K / L', 'safety · mute · shifty — on rails J/L lift a foot'],
    ['I (+A/D)', 'nose butter — I presses the tips, A/D spins'],
    ['R', 'restart run'],
  ],
  speedUnit: 'km/h',
  score: 'SCORE',
  combo: 'COMBO',
  go: 'DROP!',
  clean: 'CLEAN',
  sketchy: 'SKETCHY',
  bail: 'BAILED',
  air: 'Air',
  backflip: 'Backflip',
  frontflip: 'Frontflip',
  double: 'Double',
  blunt: 'Safety',
  truck: 'Mute',
  shifty: 'Shifty',
  misty: 'Misty',
  cork: 'Cork',
  swap: 'Swap!',
  frontslide: 'Frontslide',
  backslide: 'Backslide',
  butter: 'Nose Butter',
  switch: 'Switch',
  rails: { box: 'Box Slide', rail: 'Rail Grind', deck: 'Deck Rail', rainbow: 'Rainbow Rail', kink: 'Kinked Rail', cannon: 'Cannon', wave: 'Wave Rail', launch: 'Cliff Cannon', ridge: 'Roof Ridge', up: 'Up Rail', tube: 'Fat Tube', down: 'Down Rail' },
  finish: 'RUN COMPLETE',
  finalScore: 'Final score',
  bestTrick: 'Best trick',
  topSpeed: 'Top speed',
  bestRun: 'Best run',
  restartHint: 'Press R to run it back',
  zoneGlades: 'THE GLADES',
  zoneCliff: 'CLIFF BAND',
  zoneRails: 'CRYSTAL CAVE',
  zoneJumps: 'XL JUMP LINE',
  zoneLodge: 'THE LODGE GAP',
  zoneRollers: 'ROLLER GARDEN',
  zoneFins: 'FINS & HIPS',
  zoneTwin: 'TWIN LINES — RED & BLACK',
  zoneRailGarden: 'RAIL GARDEN',
  zoneHips: 'TOP HIPS',
  zoneQP: 'QUARTERPIPE ALLEY',
  zoneKnuckle: 'KIMBO KNUCKLES',
  zoneSpine: 'THE SPINE',
  zoneUpRail: 'THE UP RAIL',
  zoneBigHips: 'FINALE HIPS',
  zoneTopTube: 'THE FLAT TUBE',
  zoneBarrelJump: 'BARREL JUMP',
  zoneChannel: 'CHANNEL WALLS',
  zoneVolcano: 'THE VOLCANO',
  zoneHipCamp: 'THE HIP CAMP',
  zoneButter: 'BUTTER ROLLERS',
  zoneRailPlaza: 'RAIL PLAZA',
  zoneBigJumps: 'THE BIG JUMPS',
  zoneWedges: 'WEDGE WALLS',
  zoneBlocks: 'THE BLOCK GARDEN',
  zoneGully: 'WEDGE GULLIES',
  zoneTransfer: 'TRANSFER ALLEY',
  zoneStepDown: 'THE STEP-DOWN',
  zoneFinish: 'FINISH',
  mapLabel: 'Map',
  mapNames: { bluebird: 'Bluebird Park', lax: 'Sweden Park', kimbo: 'K Sessions' },
  settings: 'SETTINGS',
  turnSens: 'Turn sensitivity',
  turnSensHint: 'Applies to carving on snow and spinning in the air',
  soundVol: 'Sound volume',
  ctlOpacity: 'Control opacity',
  rotatePhone: 'ROTATE YOUR PHONE ↻',
  rider: 'Rider',
  outfit: 'Outfit',
  grabSlot: 'Grab',
  loginSub: 'Log in or create an account to ride',
  email: 'Email',
  password: 'Password',
  logIn: 'LOG IN',
  createAccount: 'CREATE ACCOUNT',
  chooseUsername: 'CHOOSE A USERNAME',
  username: 'Username',
  usernameEmpty: 'Pick any name — it just can\'t be empty',
  next: 'NEXT',
  yourSkier: 'YOUR SKIER',
  male: 'Male',
  female: 'Female',
  skinTone: 'Skin tone',
  customize: 'CUSTOMIZE',
  confirm: 'CONFIRM',
  play: 'PLAY',
  chooseMode: 'GAME MODE',
  freeSki: 'FREE SKI',
  league: 'LEAGUE',
  leagueSoon: 'coming soon',
  back: 'BACK',
  chooseMap: 'CHOOSE A MAP',
  highScore: 'High score',
  slots: { skis: 'Skis', boots: 'Boots', pants: 'Pants', top: 'Top', gloves: 'Gloves', helmet: 'Helmet', goggles: 'Goggles', poles: 'Poles' },
  ridersTitle: 'RIDERS',
  level: 'LV',
  xpGained: 'XP earned',
  nextUnlock: 'Next unlock',
  unlocked: 'UNLOCKED',
  settingsClose: 'Done',
  menuTab: 'MENU',
  mainMenu: 'MAIN MENU',
};
